mkdir DataK
curl -L https://api.github.com/repos/ReactiveX/RxJava/tarball > DataK/RxJava.tar.gz
curl -L https://api.github.com/repos/elastic/elasticsearch/tarball > DataK/elasticsearch.tar.gz
curl -L https://api.github.com/repos/iluwatar/java-design-patterns/tarball > DataK/java-design-patterns.tar.gz
curl -L https://api.github.com/repos/square/retrofit/tarball > DataK/retrofit.tar.gz
curl -L https://api.github.com/repos/square/okhttp/tarball > DataK/okhttp.tar.gz
curl -L https://api.github.com/repos/google/guava/tarball > DataK/guava.tar.gz
curl -L https://api.github.com/repos/JakeWharton/butterknife/tarball > DataK/butterknife.tar.gz
curl -L https://api.github.com/repos/PhilJay/MPAndroidChart/tarball > DataK/MPAndroidChart.tar.gz
curl -L https://api.github.com/repos/bumptech/glide/tarball > DataK/glide.tar.gz
curl -L https://api.github.com/repos/JetBrains/kotlin/tarball > DataK/kotlin.tar.gz
curl -L https://api.github.com/repos/square/leakcanary/tarball > DataK/leakcanary.tar.gz
curl -L https://api.github.com/repos/spring-projects/spring-framework/tarball > DataK/spring-framework.tar.gz
curl -L https://api.github.com/repos/greenrobot/EventBus/tarball > DataK/EventBus.tar.gz
curl -L https://api.github.com/repos/spring-projects/spring-boot/tarball > DataK/spring-boot.tar.gz
curl -L https://api.github.com/repos/airbnb/lottie-android/tarball > DataK/lottie-android.tar.gz
curl -L https://api.github.com/repos/nostra13/Android-Universal-Image-Loader/tarball > DataK/Android-Universal-Image-Loader.tar.gz
curl -L https://api.github.com/repos/zxing/zxing/tarball > DataK/zxing.tar.gz
curl -L https://api.github.com/repos/google/iosched/tarball > DataK/iosched.tar.gz
curl -L https://api.github.com/repos/square/picasso/tarball > DataK/picasso.tar.gz
curl -L https://api.github.com/repos/ReactiveX/RxAndroid/tarball > DataK/RxAndroid.tar.gz
curl -L https://api.github.com/repos/facebook/fresco/tarball > DataK/fresco.tar.gz
curl -L https://api.github.com/repos/kdn251/interviews/tarball > DataK/interviews.tar.gz
curl -L https://api.github.com/repos/Blankj/AndroidUtilCode/tarball > DataK/AndroidUtilCode.tar.gz
curl -L https://api.github.com/repos/libgdx/libgdx/tarball > DataK/libgdx.tar.gz
curl -L https://api.github.com/repos/chrisbanes/PhotoView/tarball > DataK/PhotoView.tar.gz
curl -L https://api.github.com/repos/alibaba/dubbo/tarball > DataK/dubbo.tar.gz
curl -L https://api.github.com/repos/netty/netty/tarball > DataK/netty.tar.gz
curl -L https://api.github.com/repos/afollestad/material-dialogs/tarball > DataK/material-dialogs.tar.gz
curl -L https://api.github.com/repos/Netflix/Hystrix/tarball > DataK/Hystrix.tar.gz
curl -L https://api.github.com/repos/jfeinstein10/SlidingMenu/tarball > DataK/SlidingMenu.tar.gz
curl -L https://api.github.com/repos/alibaba/fastjson/tarball > DataK/fastjson.tar.gz
curl -L https://api.github.com/repos/lgvalle/Material-Animations/tarball > DataK/Material-Animations.tar.gz
curl -L https://api.github.com/repos/loopj/android-async-http/tarball > DataK/android-async-http.tar.gz
curl -L https://api.github.com/repos/Tencent/tinker/tarball > DataK/tinker.tar.gz
curl -L https://api.github.com/repos/CymChad/BaseRecyclerViewAdapterHelper/tarball > DataK/BaseRecyclerViewAdapterHelper.tar.gz
curl -L https://api.github.com/repos/androidannotations/androidannotations/tarball > DataK/androidannotations.tar.gz
curl -L https://api.github.com/repos/nickbutcher/plaid/tarball > DataK/plaid.tar.gz
curl -L https://api.github.com/repos/android10/Android-CleanArchitecture/tarball > DataK/Android-CleanArchitecture.tar.gz
curl -L https://api.github.com/repos/JakeWharton/ViewPagerIndicator/tarball > DataK/ViewPagerIndicator.tar.gz
curl -L https://api.github.com/repos/nathanmarz/storm/tarball > DataK/storm.tar.gz
curl -L https://api.github.com/repos/pockethub/PocketHub/tarball > DataK/PocketHub.tar.gz
curl -L https://api.github.com/repos/daimajia/AndroidSwipeLayout/tarball > DataK/AndroidSwipeLayout.tar.gz
curl -L https://api.github.com/repos/greenrobot/greenDAO/tarball > DataK/greenDAO.tar.gz
curl -L https://api.github.com/repos/facebook/stetho/tarball > DataK/stetho.tar.gz
curl -L https://api.github.com/repos/navasmdc/MaterialDesignLibrary/tarball > DataK/MaterialDesignLibrary.tar.gz
curl -L https://api.github.com/repos/realm/realm-java/tarball > DataK/realm-java.tar.gz
curl -L https://api.github.com/repos/chrisbanes/Android-PullToRefresh/tarball > DataK/Android-PullToRefresh.tar.gz
curl -L https://api.github.com/repos/googlesamples/android-UniversalMusicPlayer/tarball > DataK/android-UniversalMusicPlayer.tar.gz
curl -L https://api.github.com/repos/liaohuqiu/android-Ultra-Pull-To-Refresh/tarball > DataK/android-Ultra-Pull-To-Refresh.tar.gz
curl -L https://api.github.com/repos/WhisperSystems/Signal-Android/tarball > DataK/Signal-Android.tar.gz
curl -L https://api.github.com/repos/daimajia/AndroidViewAnimations/tarball > DataK/AndroidViewAnimations.tar.gz
curl -L https://api.github.com/repos/mikepenz/MaterialDrawer/tarball > DataK/MaterialDrawer.tar.gz
curl -L https://api.github.com/repos/ksoichiro/Android-ObservableScrollView/tarball > DataK/Android-ObservableScrollView.tar.gz
curl -L https://api.github.com/repos/hdodenhof/CircleImageView/tarball > DataK/CircleImageView.tar.gz
curl -L https://api.github.com/repos/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/tarball > DataK/FizzBuzzEnterpriseEdition.tar.gz
curl -L https://api.github.com/repos/winterbe/java8-tutorial/tarball > DataK/java8-tutorial.tar.gz
curl -L https://api.github.com/repos/google/ExoPlayer/tarball > DataK/ExoPlayer.tar.gz
curl -L https://api.github.com/repos/alibaba/druid/tarball > DataK/druid.tar.gz
curl -L https://api.github.com/repos/HannahMitt/HomeMirror/tarball > DataK/HomeMirror.tar.gz
curl -L https://api.github.com/repos/orhanobut/logger/tarball > DataK/logger.tar.gz
curl -L https://api.github.com/repos/JakeWharton/ActionBarSherlock/tarball > DataK/ActionBarSherlock.tar.gz
curl -L https://api.github.com/repos/deeplearning4j/deeplearning4j/tarball > DataK/deeplearning4j.tar.gz
curl -L https://api.github.com/repos/bazelbuild/bazel/tarball > DataK/bazel.tar.gz
curl -L https://api.github.com/repos/chrisbanes/cheesesquare/tarball > DataK/cheesesquare.tar.gz
curl -L https://api.github.com/repos/roughike/BottomBar/tarball > DataK/BottomBar.tar.gz
curl -L https://api.github.com/repos/apl-devs/AppIntro/tarball > DataK/AppIntro.tar.gz
curl -L https://api.github.com/repos/wasabeef/recyclerview-animators/tarball > DataK/recyclerview-animators.tar.gz
curl -L https://api.github.com/repos/chrisjenx/Calligraphy/tarball > DataK/Calligraphy.tar.gz
curl -L https://api.github.com/repos/airbnb/lottie-react-native/tarball > DataK/lottie-react-native.tar.gz
curl -L https://api.github.com/repos/google/agera/tarball > DataK/agera.tar.gz
curl -L https://api.github.com/repos/android/platform_frameworks_base/tarball > DataK/platform_frameworks_base.tar.gz
curl -L https://api.github.com/repos/umano/AndroidSlidingUpPanel/tarball > DataK/AndroidSlidingUpPanel.tar.gz
curl -L https://api.github.com/repos/eclipse/vert.x/tarball > DataK/vert.x.tar.gz
curl -L https://api.github.com/repos/clojure/clojure/tarball > DataK/clojure.tar.gz
curl -L https://api.github.com/repos/perwendel/spark/tarball > DataK/spark.tar.gz
curl -L https://api.github.com/repos/openzipkin/zipkin/tarball > DataK/zipkin.tar.gz
curl -L https://api.github.com/repos/Freelander/Android_Data/tarball > DataK/Android_Data.tar.gz
curl -L https://api.github.com/repos/florent37/MaterialViewPager/tarball > DataK/MaterialViewPager.tar.gz
curl -L https://api.github.com/repos/prestodb/presto/tarball > DataK/presto.tar.gz
curl -L https://api.github.com/repos/junit-team/junit4/tarball > DataK/junit4.tar.gz
curl -L https://api.github.com/repos/square/dagger/tarball > DataK/dagger.tar.gz
curl -L https://api.github.com/repos/LMAX-Exchange/disruptor/tarball > DataK/disruptor.tar.gz
curl -L https://api.github.com/repos/scwang90/SmartRefreshLayout/tarball > DataK/SmartRefreshLayout.tar.gz
curl -L https://api.github.com/repos/astuetz/PagerSlidingTabStrip/tarball > DataK/PagerSlidingTabStrip.tar.gz
curl -L https://api.github.com/repos/JakeWharton/RxBinding/tarball > DataK/RxBinding.tar.gz
curl -L https://api.github.com/repos/Bearded-Hen/Android-Bootstrap/tarball > DataK/Android-Bootstrap.tar.gz
curl -L https://api.github.com/repos/apache/kafka/tarball > DataK/kafka.tar.gz
curl -L https://api.github.com/repos/alibaba/vlayout/tarball > DataK/vlayout.tar.gz
curl -L https://api.github.com/repos/dropwizard/dropwizard/tarball > DataK/dropwizard.tar.gz
curl -L https://api.github.com/repos/google/physical-web/tarball > DataK/physical-web.tar.gz
curl -L https://api.github.com/repos/cymcsg/UltimateRecyclerView/tarball > DataK/UltimateRecyclerView.tar.gz
curl -L https://api.github.com/repos/JackyAndroid/AndroidInterview-Q-A/tarball > DataK/AndroidInterview-Q-A.tar.gz
curl -L https://api.github.com/repos/Yalantis/uCrop/tarball > DataK/uCrop.tar.gz
curl -L https://api.github.com/repos/Bilibili/DanmakuFlameMaster/tarball > DataK/DanmakuFlameMaster.tar.gz
curl -L https://api.github.com/repos/81813780/AVLoadingIndicatorView/tarball > DataK/AVLoadingIndicatorView.tar.gz
curl -L https://api.github.com/repos/jeasonlzy/okhttp-OkGo/tarball > DataK/okhttp-OkGo.tar.gz
curl -L https://api.github.com/repos/Curzibn/Luban/tarball > DataK/Luban.tar.gz
curl -L https://api.github.com/repos/Netflix/SimianArmy/tarball > DataK/SimianArmy.tar.gz
curl -L https://api.github.com/repos/hongyangAndroid/okhttputils/tarball > DataK/okhttputils.tar.gz
curl -L https://api.github.com/repos/mybatis/mybatis-3/tarball > DataK/mybatis-3.tar.gz
curl -L https://api.github.com/repos/kaushikgopal/RxJava-Android-Samples/tarball > DataK/RxJava-Android-Samples.tar.gz
curl -L https://api.github.com/repos/xetorthio/jedis/tarball > DataK/jedis.tar.gz
curl -L https://api.github.com/repos/skylot/jadx/tarball > DataK/jadx.tar.gz
curl -L https://api.github.com/repos/google/guice/tarball > DataK/guice.tar.gz
curl -L https://api.github.com/repos/google/auto/tarball > DataK/auto.tar.gz
curl -L https://api.github.com/repos/nhaarman/ListViewAnimations/tarball > DataK/ListViewAnimations.tar.gz
curl -L https://api.github.com/repos/permissions-dispatcher/PermissionsDispatcher/tarball > DataK/PermissionsDispatcher.tar.gz
curl -L https://api.github.com/repos/hongyangAndroid/AndroidAutoLayout/tarball > DataK/AndroidAutoLayout.tar.gz
curl -L https://api.github.com/repos/Tencent/VasSonic/tarball > DataK/VasSonic.tar.gz
curl -L https://api.github.com/repos/koush/ion/tarball > DataK/ion.tar.gz
curl -L https://api.github.com/repos/druid-io/druid/tarball > DataK/druid.tar.gz
curl -L https://api.github.com/repos/gradle/gradle/tarball > DataK/gradle.tar.gz
curl -L https://api.github.com/repos/JakeWharton/hugo/tarball > DataK/hugo.tar.gz
curl -L https://api.github.com/repos/mockito/mockito/tarball > DataK/mockito.tar.gz
curl -L https://api.github.com/repos/code4craft/webmagic/tarball > DataK/webmagic.tar.gz
curl -L https://api.github.com/repos/brettwooldridge/HikariCP/tarball > DataK/HikariCP.tar.gz
curl -L https://api.github.com/repos/Bigkoo/Android-PickerView/tarball > DataK/Android-PickerView.tar.gz
curl -L https://api.github.com/repos/geeeeeeeeek/WeChatLuckyMoney/tarball > DataK/WeChatLuckyMoney.tar.gz
curl -L https://api.github.com/repos/pedrovgs/EffectiveAndroidUI/tarball > DataK/EffectiveAndroidUI.tar.gz
curl -L https://api.github.com/repos/aritraroy/UltimateAndroidReference/tarball > DataK/UltimateAndroidReference.tar.gz
curl -L https://api.github.com/repos/dropwizard/metrics/tarball > DataK/metrics.tar.gz
curl -L https://api.github.com/repos/DroidPluginTeam/DroidPlugin/tarball > DataK/DroidPlugin.tar.gz
curl -L https://api.github.com/repos/rey5137/material/tarball > DataK/material.tar.gz
curl -L https://api.github.com/repos/facebook/buck/tarball > DataK/buck.tar.gz
curl -L https://api.github.com/repos/alibaba/atlas/tarball > DataK/atlas.tar.gz
